### PR TITLE
Server

### PR DESCRIPTION
**Pull request by prologic**
Okay this works now (*at least locally on Linux*) :)

Have a play!

### CODE REVIEW

**Comment by oss6** [comment]
Awesome! Just tried it!

**Comment by prologic** [comment]
And it works okay so far? :) It's really rough; but it's a start!

**Comment by oss6** [comment]
Yep it works. One question: you listen to changes on the content directory, right?

**Comment by prologic** [comment]
Yes; as per how ``FileWatcher()`` is configured.

**Comment by oss6** [comment]
Ahh ok just saw it in server.py . Thanks for the support! :+1:

**Comment by prologic** [comment]
No problems! Coding up worker/subprocess now :)

**Pull request merged**
